In [213]:
import pandas as pd

In [214]:
# File names
## Import
csvFile = 'Video_Games.csv'

## Export
excelFileName = 'ficheiro.xlsx'
tab1Name = 'Raw Data'
tab2Name = 'Platform Rank'

# Pandas CSV configuration
encodingName = 'utf8'
separator = ','

# Pandas XLS configuration
engineName = 'xlsxwriter'

Global Variables

In [215]:

def extract_base(inCSVName):
    load_file = pd.read_csv(inCSVName,sep=separator,encoding=encodingName)
    return load_file

Essa função é reponsável pelo load de um ficheiro CSV

In [216]:
def transform_remove_index(inFile):
    return inFile.drop(inFile.columns[0], axis=1)

Essa função é responsável por remover a primeira coluna de index do ficheiro o parâmetro axis=1 indica que o drop é na coluna.

In [217]:
def soma_global_sales_platform(inFile):
    file = inFile.groupby('Platform')['Global_Sales'].sum().reset_index()
    file = file.sort_values(by='Global_Sales', ascending = False).reset_index()
    return file

Função responsável por fazer um group by na coluna Platform e somar os valores de Global_Sales
O reset index cria indexes para a nova lista criada
A função sort_values ordena os dados

In [218]:
def write_xls(inWriter,inFile,inTab):
    inFile.to_excel(inWriter, sheet_name=inTab,index=False)

Essa função recebe como parâmetro o pd.ExcelWriter, o file e a tab do excel e escreve no ficheiro

In [219]:
writer = pd.ExcelWriter(excelFileName, engine=engineName)

file = extract_base(csvFile)

file = transform_remove_index(file)
write_xls(writer,file,tab1Name)

maxGlobalPlatform = soma_global_sales_platform(file)
write_xls(writer,maxGlobalPlatform,tab2Name)

writer.close()

In [220]:
file.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [221]:
for index, row in file.iterrows():
    if pd.isnull(row['Global_Sales']):
        print(row)  
        break

In [222]:
file.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

Validar se a coluna "Global Sales" tem nulls

In [235]:
def filter_global_sales_not_null(file,column):
    try:
        filtered_file= file[file[column].notnull()]
        return filtered_file
    except:
        print(f'Column {column} not in DataFrame')

Função para filtrar valores não nulls da coluna. Se a coluna não existir no df, devolve mensagem a dar nota que a coluna não existe.

In [236]:
file=filter_global_sales_not_null(file,'Global_Sales')

In [237]:
file.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Diferença
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E,0.01
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN,0.00
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,-0.00
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E,0.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN,0.01

In [238]:
for index, row in file.iterrows():
    if pd.isnull(row['Global_Sales']):
        print(row)  
        break

Teste se existem valores null em Global_Sales

In [227]:
for index, row in file.iterrows():
    if row['NA_Sales']+row['EU_Sales']+row['JP_Sales']+row['Other_Sales']!=row['Global_Sales']:
        print(row)
        break

Name               Wii Sports
Platform                  Wii
Year_of_Release        2006.0
Genre                  Sports
Publisher            Nintendo
NA_Sales                41.36
EU_Sales                28.96
JP_Sales                 3.77
Other_Sales              8.45
Global_Sales            82.53
Critic_Score             76.0
Critic_Count             51.0
User_Score                  8
User_Count              322.0
Developer            Nintendo
Rating                      E
Name: 0, dtype: object

Validar se existem linhas em que NA_Sales+EU_Sales+JP_Sales+Other_Sales é diferente de Global_Sales

In [228]:
countdif=(file['NA_Sales']+file['EU_Sales']+file['JP_Sales']+file['Other_Sales']!=file['Global_Sales']).sum()
print(countdif)

6910

Nº de linhas em que NA_Sales+EU_Sales+JP_Sales+Other_Sales é diferente de Global_Sales

In [229]:
file['Diferença']=file['NA_Sales']+file['EU_Sales']+file['JP_Sales']+file['Other_Sales']-file['Global_Sales']

Criar Coluna com Global Sales menos restantes

In [230]:
file['Diferença']=file['Diferença'].round(2)

Arredondar valor da coluna para duas casas decimais

In [231]:
file

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Diferença
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E,0.01
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN,0.00
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,-0.00
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E,0.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16923,Aliens: Colonial Marines,PS3,2013.0,Shooter,Sega,0.20,0.29,0.00,0.11,0.60,43.0,25.0,3.6,295.0,Gearbox Software,M,0.00
16924,Backyard Wrestling: Don't Try This at Home,PS2,2003.0,Fighting,Eidos Interactive,0.30,0.23,0.00,0.08,0.60,51.0,24.0,7.8,29.0,Paradox Development,M,0.01
16925,Yakuza: Dead Souls,PS3,2011.0,Shooter,Sega,0.09,0.06,0.42,0.03,0.60,64.0,55.0,7.4,69.0,Ryu ga Gotoku Studios,M,0.00
16926,Fight Night Round 2,XB,2005.0,Fighting,Electronic Arts,0.42,0.16,0.00,0.02,0.60,88.0,48.0,8.8,27.0,EA Sports,T,0.00
16927,MonHun Nikki: Poka Poka Ailu Mura,PSP,2010.0,Role-Playing,Capcom,0.00,0.00,0.60,0.00,0.60,NaN,NaN,NaN,NaN,NaN,NaN,0.00

In [232]:
filtered_gbs= file[file['Diferença']>0]

Filtrar linhas em que há diferença

In [233]:
filtered_gbs

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Diferença
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E,0.01
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN,0.01
14,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,15.00,4.89,0.24,1.69,21.81,61.0,45.0,6.3,106.0,Good Science Studio,E,0.01
15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.01,8.49,2.53,1.77,21.79,80.0,33.0,7.4,52.0,Nintendo,E,0.01
16,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.02,9.09,0.98,3.96,21.04,97.0,50.0,8.2,3994.0,Rockstar North,M,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16891,Tearaway,PSV,2013.0,Adventure,Sony Computer Entertainment Europe,0.14,0.34,0.00,0.14,0.61,87.0,82.0,8.9,391.0,Media Molecule,E,0.01
16896,Borderlands: The Pre-Sequel,PS3,2014.0,Shooter,Take-Two Interactive,0.26,0.21,0.05,0.10,0.61,77.0,24.0,6.3,130.0,2K Australia,M,0.01
16918,Dark Souls II,PS4,2015.0,Role-Playing,Namco Bandai Games,0.21,0.23,0.08,0.09,0.60,NaN,NaN,NaN,NaN,NaN,NaN,0.01
16922,Wave Race: Blue Storm,GC,2001.0,Racing,Nintendo,0.40,0.10,0.09,0.02,0.60,80.0,21.0,8.3,29.0,Nintendo,E,0.01
16924,Backyard Wrestling: Don't Try This at Home,PS2,2003.0,Fighting,Eidos Interactive,0.30,0.23,0.00,0.08,0.60,51.0,24.0,7.8,29.0,Paradox Development,M,0.01

In [234]:
print(file['Diferença'].mean())

-0.00024870037807183363

Média das diferenças